name: Terraform AWS CI-CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: terraform

  TF_VAR_spoke_account_id: "434097521299"
  TF_VAR_allow_external_ram_principals: "true"

  TF_VAR_subnets: |
    {
      "private_1": {
        "cidr_block": "10.0.0.0/24",
        "availability_zone": "ap-south-1a",
        "public": false
      },
      "public_1": {
        "cidr_block": "10.0.2.0/24",
        "availability_zone": "ap-south-1a",
        "public": true
      },
      "private_2": {
        "cidr_block": "10.0.1.0/24",
        "availability_zone": "ap-south-1b",
        "public": false
      },
      "public_2": {
        "cidr_block": "10.0.3.0/24",
        "availability_zone": "ap-south-1b",
        "public": true
      }
    }

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:

      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Configure AWS using GitHub OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-test-role
          aws-region: ${{ env.AWS_REGION }}

      # 4. Check AWS identity
      - name: Check AWS Identity
        run: aws sts get-caller-identity

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # 6. Terraform Format Check
      - name: Terraform Format
        run: terraform fmt 

      # 7. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 8. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false

      # 9. Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve  