name: Terraform AWS CI-CD

on:
  push:
    branches:  
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: terraform

  TF_VAR_spoke_account_id: "434097521299"
  TF_VAR_allow_external_ram_principals: "true"

  TF_VAR_subnets: |
    {
      "private_1": {
        "cidr_block": "10.0.0.0/24",
        "availability_zone": "ap-south-1a",
        "public": false
      },
      "public_1": {
        "cidr_block": "10.0.2.0/24",
        "availability_zone": "ap-south-1a",
        "public": true
      },
      "private_2": {
        "cidr_block": "10.0.1.0/24",
        "availability_zone": "ap-south-1b",
        "public": false
      },
      "public_2": {
        "cidr_block": "10.0.3.0/24",
        "availability_zone": "ap-south-1b",
        "public": true
      }
    }

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-test-role
          aws-region: ap-south-1        

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate   

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve             